//This is demo of modeling stochastic systemts by divisive data resorting algorithm,
//developed by Andrew Polar and Mike Poluektov.
//The data is generated by rolling two sets of dice with different quantities.
//There is also random variable, which is the probability switch between either of these sets.
//The data set is generated by DataHolder dh = new DataHolder(10, 2000);
//The model predicts distribution for new data, not used in training.
//The main accuracy metric is the relative distance between two nested median trees.
//The second accuracy metric is Cramer vom Mises of order one, mean magnitude of difference for
//cumulative functions.
//Code written by Andrew Polar.

using System;
using System.Collections.Generic;

namespace VDice
{
    internal class Program
    {
        static void Main(string[] args)
        {
            DataHolder dh = new DataHolder(10, 2000);
            dh.MakeDataset();

            //Expectation model
            //KolmogorovModel km_expectaion = new KolmogorovModel(dh._inputs, dh._target, new int[] { 3, 3, 3 });
            //int NLeaves = 7;
            //int[] linearBlocksPerRootInput = new int[NLeaves];
            //for (int m = 0; m < NLeaves; ++m)
            //{
            //    linearBlocksPerRootInput[m] = 3;
            //}
            //km_expectaion.GenerateInitialOperators(NLeaves, linearBlocksPerRootInput);
            //km_expectaion.BuildRepresentation(500, 0.01, 0.01);
            //double rdist = km_expectaion.ComputeAccuracy();
            //Console.WriteLine("Relative distance for expectation model (self) {0:0.0000}", rdist);
            //////////////////////////////////////////////////////////////////////////////////////

            //Variance model
            //List<double> residuals = new List<double>();
            //for (int i = 0; i < dh._inputs.Count; ++i)
            //{
            //    double y = km_expectaion.ComputeOutput(dh._inputs[i]);
            //    residuals.Add((y - dh._target[i]) * (y - dh._target[i]));
            //}

            //KolmogorovModel km_variance = new KolmogorovModel(dh._inputs, residuals, new int[] { 3, 3, 3 });
            //int NL = 7;
            //int[] blocks = new int[NL];
            //for (int m = 0; m < NL; ++m)
            //{
            //    blocks[m] = 3;
            //}
            //km_variance.GenerateInitialOperators(NL, blocks);
            //km_variance.BuildRepresentation(300, 0.05, 0.05);
            //double rdist2 = km_variance.ComputeAccuracy();
            //Console.WriteLine("Relative distance for variance model    (self) {0:0.0000}", rdist2);
            ///////////////////////////////////////////////////////////////////////////////////////
  
            DateTime start = DateTime.Now;
            Console.WriteLine("Resorting...");

            //Sliding window model
            Resorter resorter = new Resorter();
            resorter.ReadData(dh);
            resorter.Resort(1);
            resorter.Resort(2);
            resorter.Resort(4);
            resorter.Resort(8);
            resorter.Resort(16);
            resorter.Resort(32);
 
            SlidingKMEnsemple slider = new SlidingKMEnsemple(dh._inputs, dh._target);
            slider.BuildModels(16, 64);

            DateTime end = DateTime.Now;
            TimeSpan duration = end - start;
            double time = duration.Minutes * 60.0 + duration.Seconds + duration.Milliseconds / 1000.0;
            Console.WriteLine("Processing time for DDR {0:####.00} seconds", time);

            //Accuracy test
            int NTests = 100;
            double mean_dist = 0.0;
            double mean_CVM = 0.0;
            for (int i = 0; i < NTests; ++i)
            {
                double[] randomInput = dh.MakeRandomInput();
                //double predictedVar = km_variance.ComputeOutput(randomInput);
                //double[] knn = Static.GetKNNSample(dh._inputs, dh._target, randomInput, predictedVar);
                double[] monte_carlo = dh.GetMonteCarloSample(randomInput, 4096);
                double[] ddr = slider.GetOutput(randomInput, 0.2, 10);
                List<double> monte_carlo_list = new List<double>(monte_carlo);
                List<double> ddr_list = new List<double>(ddr);

                List<double> monte_carlo_medians = Static.MedianSplit(monte_carlo, 5);
                List<double> ddr_medians = Static.MedianSplit(ddr, 5);               
                mean_dist += Static.relativeDistance(monte_carlo_medians.ToArray(), ddr_medians.ToArray());
                mean_CVM += Static.CVM(monte_carlo_list, ddr_list);
                //foreach (double s in ddr_medians)
                //{
                //    Console.Write("{0:0.00} ", s);
                //}
                //Console.WriteLine();

                //foreach (double s in monte_carlo_medians)
                //{
                //    Console.Write("{0:0.00} ", s);
                //}
                //Console.WriteLine("\n");
            }
            mean_dist /= NTests;
            mean_CVM /= NTests;
            Console.WriteLine("Accuracy metric mean median tree {0:0.0000}", mean_dist);
            Console.WriteLine("Accuracy metric Cramer von Mises order one {0:0.0000}", mean_CVM);
        }
    }
}


